export const languages= {
    English:'en',
    Malayalam:'ml',
    Hindi:'hi',
    Tamil:'ta',
    Kannada:'kn',
    French:'fr',
    Spanish:'es',
    Portuguese:'pt',
    Italian:'it',
    Russian:'ru',
    Sweedish:'sv',
    Dutch:'nl',
    Arabic:'ar',
    Turkish:'tr',
    German:'de',
    Danish:'da',
    Greek:'el',
};

export const languagesList = ["English",
"Malayalam",
"Hindi",
"Tamil",
"Kannada",
"French",
"Spanish",
"Portuguese",
"Italian",
"Russian",
"Sweedish",
"Dutch",
"Arabic",
"Turkish",
"German",
"Danish",
"Greek",
];